# fly.toml app configuration file generated for moby-website on 2024-01-08T23:01:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moby-website"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  AUTOMAILER_URL = "https://automailer.moby-it.com/send-email"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
